// Generated by CoffeeScript 1.4.0
(function() {
  var tooltip;

  $(function() {
    var cos, data, i, options, plot, previousPoint, sin, _i;
    sin = [];
    cos = [];
    for (i = _i = 0; _i <= 29; i = ++_i) {
      sin.push([i / 2, Math.sin(i / 2)]);
      cos.push([i / 2, Math.cos(i / 2)]);
    }
    data = [
      {
        data: sin,
        label: "sin(x)",
        color: "#BA1E20"
      }, {
        data: cos,
        label: "cos(x)",
        color: "#459D1C"
      }
    ];
    options = {
      series: {
        lines: {
          show: true
        },
        points: {
          show: true
        }
      },
      grid: {
        hoverable: true,
        clickable: true
      },
      yaxis: {
        min: -1.6,
        max: 1.6
      }
    };
    plot = $.plot($(".chart"), data, options);
    previousPoint = null;
    return $(".chart").bind("plothover", function(event, pos, item) {
      var x, y;
      if (item) {
        if (previousPoint !== item.dataIndex) {
          previousPoint = item.dataIndex;
          $('.tip').fadeOut(200, function() {
            return $(this).remove();
          });
          x = item.datapoint[0].toFixed(2);
          y = item.datapoint[1].toFixed(2);
          return tooltip(item.pageX, item.pageY, item.series.label + " of " + x + " = " + y);
        }
      } else {
        $('.tip').fadeOut(200, function() {
          return $(this).remove();
        });
        return previousPoint = null;
      }
    });
  });

  tooltip = function(x, y, contents) {
    return $('<div id="tooltip" class="tip">' + contents + '</div>').css({
      top: y + 5,
      left: x + 5
    }).appendTo("body").fadeIn(200);
  };

}).call(this);
