// Generated by CoffeeScript 1.4.0
(function() {
  var drawMap, japanMap;

  japanMap = "m 343.07048,177.31508 -25.88119,27.18832 1.29708,27.17825 -10.36655,22.00001 3.89123,12.9406 -12.9406,19.41592 -34.9607,12.95064 -47.8812,1.28702 -38.82179,31.06949 -18.10877,-10.3565 -1.29708,-19.42596 -46.60422,5.19835 -32.376628,12.9406 H 47.960627 l 27.178265,20.70292 -18.128901,45.30715 -18.10878,11.65358 -12.940595,-10.36655 6.465268,-24.58411 -16.811706,-7.76234 -10.3665495,-18.13895 24.5841075,-9.04937 14.23767,-16.83181 27.198365,-14.22763 20.712988,-18.12888 53.049401,-7.7724 29.7724,5.18831 28.47533,-47.90131 18.12891,12.95065 38.82176,-27.18832 15.53475,-10.34644 16.83183,-33.65358 -3.89124,-29.77241 11.64352,-18.12891 28.47533,-3.88117 14.23767,37.54481 v -22 44.00002 z m 73.78249,-129.436085 19.40587,-11.653572 5.18828,29.772412 -40.11884,7.762341 -23.28704,27.178264 -42.73311,-19.415912 -14.21756,29.782452 -31.06948,1.28703 -3.89122,-27.178261 14.23766,-20.712987 28.47533,-1.287023 7.7724,-37.544805 7.75229,-22.0000107 32.36657,28.4753287 20.71299,9.059425 -19.40587,-6.475328 38.81173,12.950646 z M 85.495381,331.34533 l 14.23767,-15.53475 15.534749,2.5841 11.66362,-11.63346 19.40586,6.46527 3.90128,9.04936 -15.54479,16.83182 -11.64353,-9.05941 -12.94058,6.46526 -7.7724,15.53474 -18.108782,-7.76234 1.266903,-12.94059 z";

  drawMap = function() {
    var $map, japan, lastWidth, paper, pos, rect, width;
    paper = null;
    rect = null;
    japan = null;
    lastWidth = 0;
    $map = $("#map");
    width = $map.width();
    pos = $map.position();
    Raphael("map", width, width / 2, function() {
      var japanScale, japanX, trans;
      paper = this;
      rect = this.rect(0, 0, width, width / 2, 10).attr({
        stroke: "none",
        fill: "0-#9bb7cb-#adc8da"
      });
      this.setStart();
      this.path(japanMap).attr({
        stroke: "#ccc6ae",
        fill: "#f0efeb",
        "stroke-opacity": 0.25
      });
      japan = this.setFinish();
      japanX = width * 7 / 32;
      japanScale = width / 800;
      trans = "t" + japanX + ",0s" + japanScale + "," + japanScale + ",0,0";
      return japan.transform(trans);
    });
    lastWidth = width;
    return $(window).resize(function() {
      var japanScale, japanX, trans;
      width = $("#map").width();
      if (width !== lastWidth) {
        paper.setSize(width, width / 2);
        rect.attr({
          width: width,
          height: width / 2
        });
        japanX = width * 7 / 32;
        japanScale = width / 800;
        trans = "t" + japanX + ",0s" + japanScale + "," + japanScale + ",0,0";
        japan.transform(trans);
      }
      return lastWidth = width;
    });
  };

  $(function() {
    return drawMap();
  });

}).call(this);
