// Generated by CoffeeScript 1.4.0
(function() {
  var parseData;

  $(function() {
    var data, getRandomData, index, options, plot, pre, update;
    $.getJSON('paths.php', function(data) {
      return $('.data-table').dataTable({
        sDom: "<'row-fluid'<'span6'f><'span6'p>r>t<'row-fluid'>",
        sPaginationType: "bootstrap",
        aaData: parseData(data[1])
      });
    });
    plot = null;
    data = null;
    options = {
      series: {
        shadowSize: 0
      },
      yaxis: {
        min: 0,
        max: 100
      },
      xaxis: {
        show: false
      }
    };
    update = function() {
      plot.setData([getRandomData()]);
      return plot.draw();
    };
    pre = null;
    getRandomData = function() {
      var d, i, res, _i, _len;
      pre = data[0];
      data = data.slice(1);
      data.push(pre + Math.random() * 50 - 25);
      res = [];
      for (i = _i = 0, _len = data.length; _i < _len; i = ++_i) {
        d = data[i];
        res.push([i, d]);
      }
      return res;
    };
    index = null;
    $('#modal').on('shown', function() {
      var num;
      data = (function() {
        var _i, _results;
        _results = [];
        for (num = _i = 1; _i <= 100; num = ++_i) {
          _results.push(50);
        }
        return _results;
      })();
      plot = $.plot($("#plot-chart"), [getRandomData()], options);
      return index = setInterval(update, 50);
    });
    return $('#modal').on('hidden', function() {
      return clearInterval(index);
    });
  });

  parseData = function(data) {
    var array, d, _i, _len;
    array = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      d = data[_i];
      array.push([d.sourceID, d.destID, d.timeDelay, "<a data-toggle=\"modal\" data-target=\"#modal\"><i class=\"icon-zoom-in\"></i></a>"]);
    }
    return array;
  };

}).call(this);
